services:
  camera:
    profiles: [production]
    image: camera:production
    build:
      context: .
      target: production
      args:
        VERSION: ${VERSION:-dev}
    network_mode: host
    volumes:
      - ./camera.yaml:/app/camera.yaml:ro
      - ./storage:/data
    restart: unless-stopped

  camera-dev:
    profiles: [development]
    image: camera:development
    build:
      context: .
      target: development
    network_mode: host
    #user: "${UID}:${GID}"
    volumes:
      - .:/app
      - ./storage:/data
      - frontend_node_modules:/app/frontend/node_modules
    environment:
      - VERSION=${VERSION:-dev}
      - GOCACHE=/app/.cache/go-build
      - HOME=/tmp
    command: sh -c "cd frontend && yarn build && cd .. && go run -ldflags=\"-X main.version=$$VERSION\" ./cmd/camera --config /app/camera.yaml"
    restart: "no"

volumes:
  frontend_node_modules:
